spring.application.name=parking-backend

spring.datasource.url=jdbc:h2:mem:atlasbank
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=prueba
spring.datasource.password=

spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

server.servlet.context-path=/neo

# Precarga data.sql (ver src/main/resources/data.sql) despues de que Hibernate cree el esquema
spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always

